language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: OLs2VI0Uaw9TWAldw2kWTgoo1sRXygAPoxDhgOAcLeWC+fdloiaesRK7RSb9W46BOxYQS4co46KDQk6BFIZCqB8/BW8m6NXpiX7rpSQknxoNUUsEUMlXQ3i9iVf4tcPmz9GT4ORMmCzpp46bQRrGRbOTsDPTz3XFhomVzMmQHL0k/gM+ZMdA9H2c9KBAiTDXzagtaXQKCX+WtvEMNqggI4wTLBuk2FGCLUKb0pvyOC6jvBN8cglrf/MCyPx4vZZFxEfcNCu6EM7WSp8NJtQ4+5HUU9VZTSxA34FkLf2r65rHvu3VZBX6ky/iwvdNBiIc1+AIBKVFIrx9l3Ug0Y4XfJ/vE6GubsjK1G5y9y7TOm9Df2SgJ3viBA4aPQAy/bXzHJq1BewxxFdeuH0SjvHIRwuRgkih72AMAqlad1pLVin0kbPqXDTLNcq29EHsHoz4UU7Iu1mY1SlkoDArCfO5mFIn61K4YNMATMoxTMaAliJ8K6zlq8NBm2Eu9cEUuV3RCOZYZgqsABS6fopK4A42fkZYxFtFgjoNRPppjkT37r/bfGUhTfZk9feTIN5aliVjdylrrjhTExOxXSoCjMV+164pwOQ1oyq4f5F0MpDVLC5vCymC82T1Eu9XgnhaM4vbDsCquyxfUGUbvubRA16wbduN87CaUgBd2ez+Z4jWz4c=
    on_start: always
    on_success: always
