<?php

/**
 * @file
 * Contains nble_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nble_core_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['name']['#description']='Enter your NBLE username <em>(non-UNB/STU patrons)</em>.';
  if (!\Drupal::currentUser()->isAuthenticated()) {
    $messenger = \Drupal::messenger();
    $messenger->addMessage(
      t('UNB/STU patrons must sign in using <strong>@auth_link</strong>.',
        [
          '@auth_link' => Link::fromTextAndUrl(
            t('Secure Services Login'),
            Url::fromUri('base:/saml/login')
          )->toString(),
        ]
      ),
      $messenger::TYPE_WARNING,
      FALSE
    );
    array_push($form['#validate'], '_nble_core_validate_final');
  }
}

/**
 * Implements hook_help().
 */
function nble_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nble_core module.
    case 'help.page.nble_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides core functionality for the NBLE site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nble_core_theme() {
  return [
    'nble_core' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_node_presave().
 */
function nble_core_node_presave($node) {
  // Trim leading/trailing whitespace from title input.
  $input_title = $node
    ->get('title')
    ->getString();
  $title = $input_title ? trim($input_title) : 'Undefined!';
  if ($title != $input_title) {
    $node->setTitle($title);
  }

  switch ($node->getType()) {
    case 'encyclopedia_item':
      // Set listing title and section field defaults, if applicable.
      if ($node->hasField('field_listing_title')) {
        $listing_title = trim($node->get('field_listing_title')->getString());
        $listing_title = (empty($listing_title)) ? $input_title : $listing_title;
      }
      else {
        $listing_title = NULL;
      }

      if (empty($node->get('field_listing_title')->getValue())) {
        $names = explode(' ', $listing_title);
        if ($names[0] === 'The') {
          $first_names = ', ' . array_shift($names);
          $last_name = (!empty($names)) ? implode(' ', $names) : NULL;
        }
        else {
          $last_name = array_pop($names);
          $first_names = (!empty($names)) ? ', ' . implode(' ', $names) : NULL;
        }
        $listing_title = $last_name . $first_names;
        $node->set('field_listing_title', $listing_title);
      }

      if ($node->hasField('field_glossary_section') &&
        empty($node->get('field_glossary_section')->getValue())) {
        // Don't use 't' for section for titles that begin with 'The'.
        $title = str_ireplace('the ', '', $listing_title);
        $listing_section = substr(trim($title), 0, 1);
        $node->set('field_glossary_section', strtoupper($listing_section[0]));
      }
      break;
  }
}

/**
 * Form validation callback.
 *
 * Alter text of error messages, removing request/reset password url references.
 * Based from https://www.drupal.org/sandbox/ekes/emaillogin.
 *
 * @see nblce_core_form_user_login_form_alter()
 */
function _nble_core_validate_final(array &$form, FormStateInterface $form_state) {
  $changed = FALSE;
  if (($errors = $form_state->getErrors()) && !empty($errors['name']) && $errors['name'] instanceof TranslatableMarkup) {
    $error = $errors['name']->getUntranslatedString();
    dump('Found USERNAME ERROR');
    if (strpos($error, 'Unrecognized username or password') !== false) {
      $errors['name'] = t(
        'Unrecognized username or password. Please try again.',
        $errors['name']->getArguments()
      );
      $changed = TRUE;
    }
    elseif (strpos($error, 'failed login attempts for this account. It is temporarily blocked') !== false) {
      $errors['name'] = t('There have been more than 5 failed login attempts for this account and
        it is temporarily blocked. Please try again later.');
      $changed = TRUE;
    }
  } else {
    // Quick & dirty purge SAML warning message on no authentication error.
    $messenger = \Drupal::messenger();
    $messenger->deleteByType($messenger::TYPE_WARNING);
  }

  if ($changed) {
    // It's clear and reset or set the protected variable by name with
    // FormState::setFormState().
    $form_state->clearErrors();
    foreach ($errors as $name => $error) {
      $form_state->setErrorByName($name, $error);
    }
  }
}
