features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
b4_cdn_version_css: 4.3.1
b4_cdn_version_js: 4.3.1
b4_navbar_schema: light
b4_navbar_bg_schema: secondary
b4_top_container: container
b4_scss: ''
