drupalAcctProvisionServer: unb_libraries_ldap
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  drupal_on_login: drupal_on_login
  drupal_on_update_create: drupal_on_update_create
ldapEntryProvisionTriggers:
  ldap_on_update_create: '0'
  ldap_on_login: '0'
  ldap_on_delete: '0'
  drupal_on_manual_creation: '0'
userUpdateCronQuery: none
userUpdateCronInterval: monthly
orphanedDrupalAcctBehavior: ldap_user_orphan_do_not_check
orphanedCheckQty: null
orphanedAccountCheckInterval: always
userConflictResolve: resolve
manualAccountConflict: conflict_show_option
acctCreation: user_settings_for_ldap
disableAdminPasswordField: true
ldapUserSyncMappings:
  drupal: {  }
  ldap: {  }
